# Generated by Django 5.1.4 on 2026-04-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='razorpay_payment_signature',
        ),
    ]
